services:
  book_management_system:
    container_name: book_management_system
    build:
      context: src/
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - database
    env_file:
      - .env
    command: >
      sh -c "uvicorn main:app --host 0.0.0.0 --port 8080 --reload --reload-dir /app"
#      sh -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8080 --reload --reload-dir /app"

  database:
    image: postgres:latest
    container_name: database
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_database:/var/lib/postgresql/data/
volumes:
  postgres_database: