services:
  book_management_system:
    container_name: book_management_system
    build:
      context: src/
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - database
    env_file:
      - .env
    command: >
      sh -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8080 --reload --reload-dir /app"
    volumes:
      - ./src/alembic:/app/alembic
      - ./certs:/app/certs

  database:
    image: postgres:latest
    container_name: database
    env_file:
      - .env
    ports:
      - "65402:5432"
    volumes:
      - postgres_book_database:/var/lib/postgresql/data/

volumes:
  postgres_book_database: