"""new fields (password_hash and email) for authors table

Revision ID: 173554c57d41
Revises: be5d58c2a5da
Create Date: 2025-03-13 19:35:20.668274

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "173554c57d41"
down_revision: Union[str, None] = "be5d58c2a5da"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("authors", sa.Column("email", sa.String(), nullable=False))
    op.add_column(
        "authors", sa.Column("password_hash", sa.LargeBinary(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("authors", "password_hash")
    op.drop_column("authors", "email")
    # ### end Alembic commands ###
